/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import it.baccan.cheshirecat.JSON;


/**
 * BodyRecallMemoryPoints
 */
@JsonPropertyOrder({
  BodyRecallMemoryPoints.JSON_PROPERTY_TEXT,
  BodyRecallMemoryPoints.JSON_PROPERTY_K,
  BodyRecallMemoryPoints.JSON_PROPERTY_METADATA
})
@JsonTypeName("Body_recall_memory_points")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BodyRecallMemoryPoints {
  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nonnull
  private String text;

  public static final String JSON_PROPERTY_K = "k";
  @javax.annotation.Nullable
  private Integer k = 100;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private String metadata = "{}";

  public BodyRecallMemoryPoints() { 
  }

  public BodyRecallMemoryPoints text(@javax.annotation.Nonnull String text) {
    this.text = text;
    return this;
  }

  /**
   * Find memories similar to this text.
   * @return text
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@javax.annotation.Nonnull String text) {
    this.text = text;
  }


  public BodyRecallMemoryPoints k(@javax.annotation.Nullable Integer k) {
    this.k = k;
    return this;
  }

  /**
   * How many memories to return.
   * @return k
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getK() {
    return k;
  }


  @JsonProperty(JSON_PROPERTY_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setK(@javax.annotation.Nullable Integer k) {
    this.k = k;
  }


  public BodyRecallMemoryPoints metadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Flat dictionary where each key-value pair represents a filter.The memory points returned will match the specified metadata criteria.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable String metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this Body_recall_memory_points object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyRecallMemoryPoints bodyRecallMemoryPoints = (BodyRecallMemoryPoints) o;
    return Objects.equals(this.text, bodyRecallMemoryPoints.text) &&
        Objects.equals(this.k, bodyRecallMemoryPoints.k) &&
        Objects.equals(this.metadata, bodyRecallMemoryPoints.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, k, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyRecallMemoryPoints {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    k: ").append(toIndentedString(k)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

