/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import it.baccan.cheshirecat.model.EmbedderModelInteraction;
import it.baccan.cheshirecat.model.LLMModelInteraction;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import it.baccan.cheshirecat.JSON;


import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import it.baccan.cheshirecat.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
@JsonDeserialize(using=ModelInteractionsInner.ModelInteractionsInnerDeserializer.class)
@JsonSerialize(using = ModelInteractionsInner.ModelInteractionsInnerSerializer.class)
public class ModelInteractionsInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ModelInteractionsInner.class.getName());

    public static class ModelInteractionsInnerSerializer extends StdSerializer<ModelInteractionsInner> {
        public ModelInteractionsInnerSerializer(Class<ModelInteractionsInner> t) {
            super(t);
        }

        public ModelInteractionsInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(ModelInteractionsInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ModelInteractionsInnerDeserializer extends StdDeserializer<ModelInteractionsInner> {
        public ModelInteractionsInnerDeserializer() {
            this(ModelInteractionsInner.class);
        }

        public ModelInteractionsInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ModelInteractionsInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize LLMModelInteraction
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(LLMModelInteraction.class);
                ModelInteractionsInner ret = new ModelInteractionsInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ModelInteractionsInner'", e);
            }

            // deserialize EmbedderModelInteraction
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(EmbedderModelInteraction.class);
                ModelInteractionsInner ret = new ModelInteractionsInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ModelInteractionsInner'", e);
            }

            throw new IOException(String.format("Failed deserialization for ModelInteractionsInner: no match found"));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ModelInteractionsInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ModelInteractionsInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public ModelInteractionsInner() {
        super("anyOf", Boolean.FALSE);
    }

    public ModelInteractionsInner(LLMModelInteraction o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ModelInteractionsInner(EmbedderModelInteraction o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("EmbedderModelInteraction", new GenericType<EmbedderModelInteraction>() {
        });
        schemas.put("LLMModelInteraction", new GenericType<LLMModelInteraction>() {
        });
        JSON.registerDescendants(ModelInteractionsInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return ModelInteractionsInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * EmbedderModelInteraction, LLMModelInteraction
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(LLMModelInteraction.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(EmbedderModelInteraction.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be EmbedderModelInteraction, LLMModelInteraction");
    }

    /**
     * Get the actual instance, which can be the following:
     * EmbedderModelInteraction, LLMModelInteraction
     *
     * @return The actual instance (EmbedderModelInteraction, LLMModelInteraction)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `LLMModelInteraction`. If the actual instance is not `LLMModelInteraction`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `LLMModelInteraction`
     * @throws ClassCastException if the instance is not `LLMModelInteraction`
     */
    public LLMModelInteraction getLLMModelInteraction() throws ClassCastException {
        return (LLMModelInteraction)super.getActualInstance();
    }

    /**
     * Get the actual instance of `EmbedderModelInteraction`. If the actual instance is not `EmbedderModelInteraction`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `EmbedderModelInteraction`
     * @throws ClassCastException if the instance is not `EmbedderModelInteraction`
     */
    public EmbedderModelInteraction getEmbedderModelInteraction() throws ClassCastException {
        return (EmbedderModelInteraction)super.getActualInstance();
    }

}

