/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.*;
import it.baccan.cheshirecat.auth.*;
import it.baccan.cheshirecat.model.HTTPValidationError;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthHandlerApi
 */
public class AuthHandlerApiTest {

    private final AuthHandlerApi api = new AuthHandlerApi();

    /**
     * Get Auth Handler Setting
     *
     * Get the settings of a specific AuthHandler
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAuthHandlerSettingTest() throws ApiException {
        //String authHandlerName = null;
        //Object response = api.getAuthHandlerSetting(authHandlerName);
        // TODO: test validations
    }

    /**
     * Get Auth Handler Settings
     *
     * Get the list of the AuthHandlers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAuthHandlerSettingsTest() throws ApiException {
        //Object response = api.getAuthHandlerSettings();
        // TODO: test validations
    }

    /**
     * Upsert Authenticator Setting
     *
     * Upsert the settings of a specific AuthHandler
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void upsertAuthenticatorSettingTest() throws ApiException {
        //String authHandlerName = null;
        //Object body = null;
        //Object response = api.upsertAuthenticatorSetting(authHandlerName, body);
        // TODO: test validations
    }

}
