/*
 * �Y~� Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Get Injected Admin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInjectedAdminTest() throws ApiException {
        Object response = api.getInjectedAdmin();
        // TODO: test validations
    }

    /**
     * Get Injected Admin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInjectedAdmin_0Test() throws ApiException {
        Object response = api.getInjectedAdmin_0();
        // TODO: test validations
    }

    /**
     * Get Injected Admin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInjectedAdmin_1Test() throws ApiException {
        Object response = api.getInjectedAdmin_1();
        // TODO: test validations
    }

}
