/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.*;
import it.baccan.cheshirecat.auth.*;
import it.baccan.cheshirecat.model.CatMessage;
import it.baccan.cheshirecat.model.HTTPValidationError;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HomeApi
 */
public class HomeApiTest {

    private final HomeApi api = new HomeApi();

    /**
     * Message With Cat
     *
     * Get a response from the Cat
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void messageWithCatTest() throws ApiException {
        //Object body = null;
        //CatMessage response = api.messageWithCat(body);
        // TODO: test validations
    }

    /**
     * Status
     *
     * Server status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void statusTest() throws ApiException {
        //Object response = api.status();
        // TODO: test validations
    }

}
