/*
 * 😸 Cheshire-Cat API
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.ApiException;
import it.baccan.cheshirecat.model.CollectionsList;
import it.baccan.cheshirecat.model.ConversationHistory;
import it.baccan.cheshirecat.model.HTTPValidationError;
import it.baccan.cheshirecat.model.MemoryRecall;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MemoryApi
 */
@Disabled
public class MemoryApiTest {

    private final MemoryApi api = new MemoryApi();

    /**
     * Delete Point In Memory
     *
     * Delete specific point in memory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePointInMemoryTest() throws ApiException {
        String collectionId = null;
        String memoryId = null;
        List<String> response = api.deletePointInMemory(collectionId, memoryId);
        // TODO: test validations
    }

    /**
     * Get Collections
     *
     * Get list of available collections
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionsTest() throws ApiException {
        CollectionsList response = api.getCollections();
        // TODO: test validations
    }

    /**
     * Get Conversation History
     *
     * Get the specified user&#39;s conversation history from working memory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConversationHistoryTest() throws ApiException {
        ConversationHistory response = api.getConversationHistory();
        // TODO: test validations
    }

    /**
     * Recall Memories From Text
     *
     * Search k memories similar to given text.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recallMemoriesFromTextTest() throws ApiException {
        String text = null;
        Integer k = null;
        MemoryRecall response = api.recallMemoriesFromText(text, k);
        // TODO: test validations
    }

    /**
     * Wipe Collections
     *
     * Delete and create all collections
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void wipeCollectionsTest() throws ApiException {
        List<String> response = api.wipeCollections();
        // TODO: test validations
    }

    /**
     * Wipe Conversation History
     *
     * Delete the specified user&#39;s conversation history from working memory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void wipeConversationHistoryTest() throws ApiException {
        List<String> response = api.wipeConversationHistory();
        // TODO: test validations
    }

    /**
     * Wipe Memory Points By Metadata
     *
     * Delete points in memory by filter
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void wipeMemoryPointsTest() throws ApiException {
        String collectionId = null;
        Object body = null;
        List<String> response = api.wipeMemoryPoints(collectionId, body);
        // TODO: test validations
    }

    /**
     * Wipe Single Collection
     *
     * Delete and recreate a collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void wipeSingleCollectionTest() throws ApiException {
        String collectionId = null;
        List<String> response = api.wipeSingleCollection(collectionId);
        // TODO: test validations
    }

}
