/*
 * �Y~� Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.ApiException;
import java.io.File;
import it.baccan.cheshirecat.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PluginsApi
 */
@Disabled
public class PluginsApiTest {

    private final PluginsApi api = new PluginsApi();

    /**
     * Delete Plugin
     *
     * Physically remove plugin.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePluginTest() throws ApiException {
        String pluginId = null;
        Object response = api.deletePlugin(pluginId);
        // TODO: test validations
    }

    /**
     * Get Available Plugins
     *
     * List available plugins
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailablePluginsTest() throws ApiException {
        String query = null;
        Object response = api.getAvailablePlugins(query);
        // TODO: test validations
    }

    /**
     * Get Plugin Details
     *
     * Returns information on a single plugin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPluginDetailsTest() throws ApiException {
        String pluginId = null;
        Object response = api.getPluginDetails(pluginId);
        // TODO: test validations
    }

    /**
     * Get Plugin Settings
     *
     * Returns the settings of a specific plugin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPluginSettingsTest() throws ApiException {
        String pluginId = null;
        Object response = api.getPluginSettings(pluginId);
        // TODO: test validations
    }

    /**
     * Get Plugins Settings
     *
     * Returns the settings of all the plugins
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPluginsSettingsTest() throws ApiException {
        Object response = api.getPluginsSettings();
        // TODO: test validations
    }

    /**
     * Install Plugin
     *
     * Install a new plugin from a zip file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void installPluginTest() throws ApiException {
        File _file = null;
        Object response = api.installPlugin(_file);
        // TODO: test validations
    }

    /**
     * Install Plugin From Registry
     *
     * Install a new plugin from registry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void installPluginFromRegistryTest() throws ApiException {
        Object body = null;
        Object response = api.installPluginFromRegistry(body);
        // TODO: test validations
    }

    /**
     * Toggle Plugin
     *
     * Enable or disable a single plugin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void togglePluginTest() throws ApiException {
        String pluginId = null;
        Object response = api.togglePlugin(pluginId);
        // TODO: test validations
    }

    /**
     * Upsert Plugin Settings
     *
     * Updates the settings of a specific plugin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void upsertPluginSettingsTest() throws ApiException {
        String pluginId = null;
        Object body = null;
        Object response = api.upsertPluginSettings(pluginId, body);
        // TODO: test validations
    }

}
