/*
 * �Y~� Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.ApiException;
import it.baccan.cheshirecat.model.BodyUploadUrl;
import java.io.File;
import it.baccan.cheshirecat.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RabbitHoleApi
 */
@Disabled
public class RabbitHoleApiTest {

    private final RabbitHoleApi api = new RabbitHoleApi();

    /**
     * Get Allowed Mimetypes
     *
     * Retrieve the allowed mimetypes that can be ingested by the Rabbit Hole
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllowedMimetypesTest() throws ApiException {
        Object response = api.getAllowedMimetypes();
        // TODO: test validations
    }

    /**
     * Upload File
     *
     * Upload a file containing text (.txt, .md, .pdf, etc.). File content will be extracted and segmented into chunks. Chunks will be then vectorized and stored into documents memory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFileTest() throws ApiException {
        File _file = null;
        Integer chunkSize = null;
        Integer chunkOverlap = null;
        Object response = api.uploadFile(_file, chunkSize, chunkOverlap);
        // TODO: test validations
    }

    /**
     * Upload Memory
     *
     * Upload a memory json file to the cat memory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadMemoryTest() throws ApiException {
        File _file = null;
        Object response = api.uploadMemory(_file);
        // TODO: test validations
    }

    /**
     * Upload Url
     *
     * Upload a url. Website content will be extracted and segmented into chunks. Chunks will be then vectorized and stored into documents memory.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadUrlTest() throws ApiException {
        BodyUploadUrl bodyUploadUrl = null;
        Object response = api.uploadUrl(bodyUploadUrl);
        // TODO: test validations
    }

}
