/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.service;

import it.baccan.cheshirecat.*;
import it.baccan.cheshirecat.auth.*;
import it.baccan.cheshirecat.model.HTTPValidationError;
import it.baccan.cheshirecat.model.UserCreate;
import it.baccan.cheshirecat.model.UserResponse;
import it.baccan.cheshirecat.model.UserUpdate;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Create User
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        //UserCreate userCreate = null;
        //UserResponse response = api.createUser(userCreate);
        // TODO: test validations
    }

    /**
     * Delete User
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        //String userId = null;
        //UserResponse response = api.deleteUser(userId);
        // TODO: test validations
    }

    /**
     * Read User
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readUserTest() throws ApiException {
        //String userId = null;
        //UserResponse response = api.readUser(userId);
        // TODO: test validations
    }

    /**
     * Read Users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readUsersTest() throws ApiException {
        //Integer skip = null;
        //Integer limit = null;
        //List<UserResponse> response = api.readUsers(skip, limit);
        // TODO: test validations
    }

    /**
     * Update User
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        //String userId = null;
        //UserUpdate userUpdate = null;
        //UserResponse response = api.updateUser(userId, userUpdate);
        // TODO: test validations
    }

}
