/*
 * �Y~� Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BodyUploadUrl
 */
public class BodyUploadUrlTest {
    private final BodyUploadUrl model = new BodyUploadUrl();

    /**
     * Model tests for BodyUploadUrl
     */
    @Test
    public void testBodyUploadUrl() {
        // TODO: test BodyUploadUrl
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'chunkSize'
     */
    @Test
    public void chunkSizeTest() {
        // TODO: test chunkSize
    }

    /**
     * Test the property 'chunkOverlap'
     */
    @Test
    public void chunkOverlapTest() {
        // TODO: test chunkOverlap
    }

}
