/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import it.baccan.cheshirecat.model.MessageWhy;
import it.baccan.cheshirecat.model.ModelInteractionsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CatMessageWhy
 */
public class CatMessageWhyTest {
    private final CatMessageWhy model = new CatMessageWhy();

    /**
     * Model tests for CatMessageWhy
     */
    @Test
    public void testCatMessageWhy() {
        // TODO: test CatMessageWhy
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'intermediateSteps'
     */
    @Test
    public void intermediateStepsTest() {
        // TODO: test intermediateSteps
    }

    /**
     * Test the property 'memory'
     */
    @Test
    public void memoryTest() {
        // TODO: test memory
    }

    /**
     * Test the property 'modelInteractions'
     */
    @Test
    public void modelInteractionsTest() {
        // TODO: test modelInteractions
    }

}
