/*
 * 😸 Cheshire-Cat API
 * Production ready AI assistant framework
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import com.fasterxml.jackson.annotation.JsonTypeName;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChunkSize
 */
public class ChunkSizeTest {
    private final ChunkSize model = new ChunkSize();

    /**
     * Model tests for ChunkSize
     */
    @Test
    public void testChunkSize() {
        // TODO: test ChunkSize
    }

}
