/*
 * 😸 Cheshire-Cat API
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import it.baccan.cheshirecat.model.QueryData;
import it.baccan.cheshirecat.model.VectorsData;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MemoryRecall
 */
public class MemoryRecallTest {
    private final MemoryRecall model = new MemoryRecall();

    /**
     * Model tests for MemoryRecall
     */
    @Test
    public void testMemoryRecall() {
        // TODO: test MemoryRecall
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'vectors'
     */
    @Test
    public void vectorsTest() {
        // TODO: test vectors
    }

}
