/*
 * 😸 Cheshire-Cat API
 * Customizable AI architecture
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.baccan.cheshirecat.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseGetAllowedMimetypes
 */
public class ResponseGetAllowedMimetypesTest {
    private final ResponseGetAllowedMimetypes model = new ResponseGetAllowedMimetypes();

    /**
     * Model tests for ResponseGetAllowedMimetypes
     */
    @Test
    public void testResponseGetAllowedMimetypes() {
        // TODO: test ResponseGetAllowedMimetypes
    }

    /**
     * Test the property 'allowed'
     */
    @Test
    public void allowedTest() {
        // TODO: test allowed
    }

}
